name: Rust CI

on:
  push:
    branches: ["main"]
    paths:
      - .github/workflows/rust-ci.yml
      - "src/main.rs"
      - "src/cli.rs"
      - "src/viralrecon.rs"
      - "src/scrnaseq.rs"
      - "src/utils.rs"
      - "cargo.toml"
      - "cargo.lock"
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build --verbose
